services:
  - type: web
    name: safereach-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: GMAPS_API_KEY
        sync: false
      - key: ACCOUNT_SID
        sync: false
      - key: AUTH_TOKEN
        sync: false
      - key: TWILIO_NUMBER
        sync: false
      - key: API_KEYS
        sync: false